### ISSUE TITLE
Iss :채팅방 프로필 이미지 삽입

### ISSUE THREAD

**Issue by ks0927** [Libienz/Spoot-Taxi-FrontEnd#10]
@Libienz 
ChatFragment의 ChatRoomAdapter에 채팅방 목록을 바인딩할때 유저이미지를 넣어야됩니다.

**Comment by Libienz** [comment]
## 1. 채팅방 목록에서 유저의 프로필 사진 렌더링 
- 다음과 같이 렌더링 됌
  ![image](https://github.com/Libienz/Spoot-Taxi-FrontEnd/assets/85234650/c32f17bb-4236-4a98-8f74-85f2913f9c67)
- 이전과 다르게 하드 코딩하여 가져온 것이 아니라 유저 url을 기반으로 가져오도록 설정된 것임
-  다만 서버 컴퓨터의 프로필 이미지 저장 디렉토리 구조가 구성된 상태에서 api가 올바르게 동작하기에 현재 나의 환경에서만 될 것임 (테스트 해보고 싶으면 서버측 코드 따라가서 적혀있는 상대경로에 폴더 만들고 테스트 해봐도 된다)
- 추가로 채팅방 이름이 12자가 넘어가면 서버에서 채팅방 이름 생성할 때 ...을 뒤에 붙이도록 설정했음 (서버 레포에 PR없이 메인 커밋했음)
