### ISSUE TITLE
Iss :매칭할 때 채팅방 구독 신청

### ISSUE THREAD

**Issue by ks0927** [Libienz/Spoot-Taxi-FrontEnd#11]
@Libienz 
MatchingFragment에서 매칭이 끝난뒤 매칭 프로그레스 팝업을 닫으면서 WebSocketManager에서 연결 및 구독 진행해야될것같습니다.

**Comment by Libienz** [comment]
해
결을 다른 방식으로 했음 
서버측에서 채팅방에 인원들 넣어버리는 것으로 해결
매칭 요청을 받은 서버가 매칭이 성사됨을 확인하고 후처리 하는 과정에서 구독할 chatRoomId를 보내는 것이 원래의 flow였으나

**Comment by Libienz** [comment]
@ks0927 요거 내가 새벽에 닫은 이슈인데 확인해줘야 함 pr 기다리기보단 업데이트 된걸로 나머지 이슈 해결하고 싶어서 내가 닫은 것 ㅇㅇ;
