### ISSUE TITLE
Iss : 채팅방 메세지 키보드문제

### ISSUE THREAD

**Issue by ks0927** [Libienz/Spoot-Taxi-FrontEnd#12]
@Libienz 
ChatRoomActivity에서 메세지를 작성할때 키보드가 화면을 가리는 현상 수정해야할것같습니다.

**Comment by Libienz** [comment]
ChatRoomActivity의 RecyclerView를 Resizable하게 설정하여 해결해야 할 듯 함 해당 작업을 iss12 브랜치에서 진행해 보겠음

**Comment by Libienz** [comment]
## 1. 입력을 위해 키보드를 띄우면 리사이클러 뷰의 요소들을 가린다.. 매번 스크롤 해주기 귀찮
   - 리사이클러 뷰의 설정을 한 줄 수정하여 채팅방이 올라오더라도 기존에 보고 있던 아이템이 묻히지 않도록 고쳤다.
   - https://github.com/Libienz/Spoot-Taxi-FrontEnd/blob/751679193a4c4c2bb63d04f94db48c9a853d3a98/app/src/main/java/com/example/spoot_taxi_front/activities/ChatRoomActivity.java#L81
   - 비슷한 고민을 한 다른 사람의 블로그를 참조 했음 (https://jason-api.tistory.com/2)
   - 위의 코드는 리사이클러뷰가 아래에서 위로 스크롤 되도록 설정한 것 
   - 아래에 있는 키보드가 나타나더라도 아래를 기준으로 뷰가 설정됨으로리사이클러뷰가 적절히 비켜줄 수 있게 된다. 👍🏻

**Comment by Libienz** [comment]
## 2. 이용자가 메시지를 전송하면 화면에 전송한 메시지가 바로 보이지 않음 
### 스크롤 한 단계 내려야 내가 보낸 메시지가 보인다... 자연스럽지 못함
   - 보낸 것이 바로바로 보이도록 smoothScrollToBottom 하도록 설정했다.
   - https://github.com/Libienz/Spoot-Taxi-FrontEnd/blob/751679193a4c4c2bb63d04f94db48c9a853d3a98/app/src/main/java/com/example/spoot_taxi_front/activities/ChatRoomActivity.java#L117-L141
- 여기에서 분기가 있는데 내가 메시지를 보낸 경우에는 현재 내가 리사이클러 뷰의 어디를 뒤지고 있든 아래로 스크롤 하도록 했고 상대가 메시지를 보낸 경우에는 내가 바닥과 가까운 경우에만 바텀으로 스크롤 하도록 했다. 
- 상대가 메시지를 보낼때마다 무조건 바닥으로 스크롤 하면 이전 대화를 찾기 힘들 것이라고 예상해서 분기를 자세히 두었음

**Comment by Libienz** [comment]
## 3. 많은 채팅방에서 사용되는 맨 아래로 스크롤 하기 버튼이 구현돼 있지 않음 
- 리사이클러뷰 영역 위에 (on position) 버튼을 띄우고 싶었는데 리니어 레이아웃으로는 불가능 했음 (vertical 혹은 horizontal로 쌓아나가니까)
- 이에 레이아웃을 constraint로 변경, 영역위에 떠 있는 floating button을 구현 했음
- ![image](https://github.com/Libienz/Spoot-Taxi-FrontEnd/assets/85234650/8a372a39-8f15-4179-8d08-f4f3a3fd9cc2)
- 해당 버튼은 현재 보고 있는 위치가 바닥이면 사라지고 바닥이 아니면 나타나게 구현되었음

**Comment by Libienz** [comment]
## 4.  리사이클러 뷰에서 위쪽의 아이템들을 살펴보고 있을 때 새로운 메시지 도착을 감지할 수 없음
- 기존 코드에서 정보를 찾기 위해 이전 대화를 관찰하는 도중 새로운 메시지가 도착해도 도착한 것을 감지할 수 없음
- 새로운 메시지가 도착하면 다음과 같이 알림을 주도록 설정했음 
- ![image](https://github.com/Libienz/Spoot-Taxi-FrontEnd/assets/85234650/4f88cc29-ff29-406a-a6e5-acdafaf71e06)
- 해당 알림 역시 맨 아래로 이동하면 사라지도록 구현

**Comment by Libienz** [comment]
채팅방 내에서 내가 불편함을 느낀 건 요 4가지 정도인 것 같고 관련해서 수정을 해봤는데 더 요구되는 것이 있다고 생각되면 말해주시와요 @ks0927

**Comment by ks0927** [comment]
1 2 3 해결내용 다 좋은것 같습니다. 4번에 대해서는 조금 이야기할거리가 있는데

> ## 4. 리사이클러 뷰에서 위쪽의 아이템들을 살펴보고 있을 때 새로운 메시지 도착을 감지할 수 없음
> * 기존 코드에서 정보를 찾기 위해 이전 대화를 관찰하는 도중 새로운 메시지가 도착해도 도착한 것을 감지할 수 없음
> * 새로운 메시지가 도착하면 다음과 같이 알림을 주도록 설정했음
> * ![image](https://user-images.githubusercontent.com/85234650/258557106-4f88cc29-ff29-406a-a6e5-acdafaf71e06.png)
> * 해당 알림 역시 맨 아래로 이동하면 사라지도록 구현

구현한 방식이 새로운 메세지가 도착했을때 저렇게 알림을 주는기능 좋습니다. 근데 혹시 어디부터가 새메세지인지 표기할수있는 기능까지는 힘들겠죠?

**Comment by Libienz** [comment]
> 1 2 3 해결내용 다 좋은것 같습니다. 4번에 대해서는 조금 이야기할거리가 있는데
> 
> > ## 4. 리사이클러 뷰에서 위쪽의 아이템들을 살펴보고 있을 때 새로운 메시지 도착을 감지할 수 없음
> > 
> > * 기존 코드에서 정보를 찾기 위해 이전 대화를 관찰하는 도중 새로운 메시지가 도착해도 도착한 것을 감지할 수 없음
> > * 새로운 메시지가 도착하면 다음과 같이 알림을 주도록 설정했음
> > * ![image](https://user-images.githubusercontent.com/85234650/258557106-4f88cc29-ff29-406a-a6e5-acdafaf71e06.png)
> > * 해당 알림 역시 맨 아래로 이동하면 사라지도록 구현
> 
> 구현한 방식이 새로운 메세지가 도착했을때 저렇게 알림을 주는기능 좋습니다. 근데 혹시 어디부터가 새메세지인지 표기할수있는 기능까지는 힘들겠죠?

안읽은 메시지를 액티비티 단에서 카운트하고 맨 밑으로 스크롤 했을 때 itemcount - 안읽은 메시지 수 해서 안읽은 아이템 표시할 수는 있을 듯?

**Comment by Libienz** [comment]
방금 좀 만져봤는데 할 수는 있을 듯 근데 우선 이 정도면 기본은 해놓은 것 같고 해당 작업은 하게 된다면 후순위로 두는 게 낫지 않을까 하네 다른 부분이 기본이 안되어 있는 부분이 많으니 급한 것 먼저 하는게 으떰??

**Comment by ks0927** [comment]
넹 후순위로 두고 나중에 생각하죠

**Comment by Libienz** [comment]
너가 따로 메모해놔주라 그러면 나머지 살펴보고 또 코멘트 달거나 아니면 pr 밀어줏메 브랜치는 delete 해주공
