### ISSUE TITLE
Iss : 채팅 메시지 전송 시 아무 입력 없이 전송하더라도 전송이 되는 이슈

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-FrontEnd#14]
아무 입력없이 전송하더라도 빈 메시지가 전송이 됌
- resource 낭비가 없도록 아무 메시지가 없다면 전송을 막아야 함 
- 전송을 막는 방법은 Button을 enable = false 할 수도 있고 msg == "" 인지 체크를 할 수도 있음
- 이외에도 전송을 막는 다양한 방법이 있을 것 같은데 자세한 스펙은 @ks0927 가 정해서 해결해 주고 해당 이슈에 내용을 공유해 주길 바람

**Comment by Libienz** [comment]
채팅방 나가기 간단한 알림 구현이 필요할 것 같다ㅇㅇ
나가고 나머지 참여자들에게 아무런 알림도 주지 않는 상황
알림을 구현해야 하는 데 구현 방법이  여러가지가 될 수 있을 것 같은데 토의를 차차 진행하자
별개의 이슈지만 소규모 작업이라 해당 이슈에 끼워넣을게 같이 작업해줘

**Comment by Libienz** [comment]
> 채팅방 나가기 간단한 알림 구현이 필요할 것 같다ㅇㅇ 나가고 나머지 참여자들에게 아무런 알림도 주지 않는 상황 알림을 구현해야 하는 데 구현 방법이 여러가지가 될 수 있을 것 같은데 토의를 차차 진행하자 별개의 이슈지만 소규모 작업이라 해당 이슈에 끼워넣을게 같이 작업해줘

문득 떠오른 아이디어인데 이전에 JPA강의에서들었던 것을 기억해보면 Item이 있고 Item을 상속하는 Book, Movie 클래스 등등이 있었던 것 기억하지? 그리고 우리는 예제에서 엔티티간 상속관계(연관관계 아님)를 관리하는 전략으로 Discriminator 전략을 사용했었지
- Discriminator 전략
   - 하나의 테이블에 상속 엔티티들의 모든 칼럼을 때려넣고 Dtype으로 구분하는 전략

이것 처럼 Message도 메시지를 상속하는 공지메시지를 만들어서 메시지와 상속관계를 불어넣은 설계는 어떨까

누군가 채팅방을 exit하거나 할 때 공지메시지를 작성해서 repo에 넣는거시지

**Comment by ks0927** [comment]
> 

음... 읽어보고 고민해봤는데  이렇게 하면 어떤 장점이 있죠? 가볍게 메시지의 senderEmail를 Administer 이런거로 해서 작성해서 보내면 안되나용? 실제로 가입할때는 학교이메일의 형식이어야하는데 'Administer'와 같은 형식은 유니크 하죠?

**Comment by Libienz** [comment]
> > > 채팅방 나가기 간단한 알림 구현이 필요할 것 같다ㅇㅇ 나가고 나머지 참여자들에게 아무런 알림도 주지 않는 상황 알림을 구현해야 하는 데 구현 방법이 여러가지가 될 수 있을 것 같은데 토의를 차차 진행하자 별개의 이슈지만 소규모 작업이라 해당 이슈에 끼워넣을게 같이 작업해줘
> > 
> > 
> > @ks0927
> > 문득 떠오른 아이디어인데 이전에 JPA강의에서들었던 것을 기억해보면 Item이 있고 Item을 상속하는 Book, Movie 클래스 등등이 있었던 것 기억하지? 그리고 우리는 예제에서 엔티티간 상속관계(연관관계 아님)를 관리하는 전략으로 Discriminator 전략을 사용했었지
> > 
> > * Discriminator 전략
> >   
> >   * 하나의 테이블에 상속 엔티티들의 모든 칼럼을 때려넣고 Dtype으로 구분하는 전략
> > 
> > 이것 처럼 Message도 메시지를 상속하는 공지메시지를 만들어서 메시지와 상속관계를 불어넣은 설계는 어떨까
> > 누군가 채팅방을 exit하거나 할 때 공지메시지를 작성해서 repo에 넣는거시지
> 
> @Libienz 음... 읽어보고 고민해봤는데 이렇게 하면 어떤 장점이 있죠? 가볍게 메시지의 senderEmail를 Administer 이런거로 해서 작성해서 보내면 안되나용? 실제로 가입할때는 학교이메일의 형식이어야하는데 'Administer'와 같은 형식은 유니크 하죠?

SystemMessage를 상속관계로 묶을 경우
1. 확장에 잘 견딘다 공지 메시지를 서버 단 에서 커스텀할 일이 생길 때 상속관계를 이용했기에 필드만 추가하면 된다.   
2. 리사이클러뷰에서 뷰타입을 분리하여 SystemMessage를 프론트 단에서 커스텀할 수있다. 

너가 말한 것처럼 모든 채팅방에 관리자를 추가해서 관리자가 보내는 메시지로 시스템 메시지를 구현하면 공지메시지의 형식과 뷰렌더링이 일반 사용자가 보낸 메시지와 똑같이 생기게 될 것이여. 서버단에서도, 뷰 커스텀 방면에서도 확장성이 음슴 
그리고 참고로 가입할 때는 학교 이메일의 형식이어야 하고 Administer로 가입할 수 있는 사용자는 아무도 없겠지만 유저의 닉네임은 유니크하지 않어 공지 메시지의 패턴을 파악한 유저가 낚시를 할 수도..?

**Comment by ks0927** [comment]
알겠습니당
