### ISSUE TITLE
Iss: Retrofit 2xx 스테이터스가 아닌 경우 응답의 body를 받아오지 않는 issue

### ISSUE THREAD

**Issue by Libienz** [Libienz/Spoot-Taxi-FrontEnd#4]
- 이전 회의에서 확인했듯이 Retrofit에서 요청을 날리고 받은 응답코드가 2xx가 아닌 경우 바디 자체를 아예 받아오지 않고 null을 주입해버립니다.  아래 코드는 널 처리가 안되어 있는 모습
https://github.com/Libienz/Spoot-Taxi-FrontEnd/blob/b0273caa3c7a854a0657e10ae465d7b27e99253c/app/src/main/java/com/example/spoot_taxi_front/activities/VerificationActivity.java#L69-L83

- 널 처리를 하면 가볍게 해결될 문제처럼 보이지만 실상 그렇지 않은 현실입니다.
- 현재 서버에서는 요청을 수행하지 못했을 때 에러에 해당하는 스테이터스를 적절히 설정하고 Dto(즉 body)에 에러메시지를 싣고 있는데 이를 꺼낼 수가 없는 상황인 거십니다. 
- 스테이터스가 2xx가 아니기에 이를 조회할 수 조차 없는 상황인 거시지요
- Retrofit을 2xx이외의 코드들도 body를 깔 수 있게 설정하거나 혹은 서버단 모든 에러메시지를 ok status로 보내는 강수를 두어야 할 것 같습니다.  성공 여부는 success 필드로 구분하고..

관련해서 의견 자유롭게 남겨주세요
해당 이슈에 관한 responseHandling작업은 서버 쪽 작업 끝나면 규약을 맞추어 작업 들어갈 것이기에 우선 이슈로 남겨놓음을 알립니다.

**Comment by ks0927** [comment]
이거는... 좀더 고민해봐야될거 같습니다... 모든 에러메시지를 ok status로 보내는 강수는... 극단적인느낌인거 같습니다

**Comment by Libienz** [comment]
아마 status 2xx 아니어도 꺼낼 수 있도록 설정하는 방법이 있을 것 같은데 우선 이슈 열어두고 서버 작업 끝내고 와서 해결합시다.

**Comment by Libienz** [comment]
body에 집착하지 않고 서버 쪽에서 에러상황에 맞는 status 코드를 전송하도록 재설계했다.
프론트측은 이제 status 코드를 기반으로 적절한 분기를 가져갈 수 있도록 구현했다!
